#SPDX-License-Identifier: MIT-0
---
# tasks file for Upload_My_Web_Page

- name: Install Nginx, PHP-FPM and Upload My Web Page
  hosts: aws_servers
  become: yes

  roles:
    - role: Upload_My_Web_Page
      when: true
